apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks1-f587"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks1-f587"
  template:
    metadata:
      labels:
        app: "aks1-f587"
    spec:
      containers:
        - name: "aks1-f587"
          image: "acr1af9d.azurecr.io/aks1"
          ports:
          - containerPort: 3001